# Generated by Django 4.1 on 2023-10-12 11:25

from django.db import migrations, models
import django.db.models.deletion
import caps.models.capability_set
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("caps", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConcreteObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=16)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Reference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        verbose_name="Reference",
                    ),
                ),
                (
                    "depth",
                    models.PositiveIntegerField(default=0, verbose_name="Share Count"),
                ),
                (
                    "capabilities",
                    models.ManyToManyField(to="caps.capability", verbose_name="Capability"),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="caps_test.reference",
                        verbose_name="Source Reference",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="caps.agent"),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="_abstract",
                        to="caps_test.concreteobject",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {("origin", "receiver", "target")},
            },
            bases=(caps.models.capability_set.BaseCapabilitySet, models.Model),
        ),
        migrations.CreateModel(
            name="ConcreteObjectReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        verbose_name="Public Reference",
                    ),
                ),
                (
                    "depth",
                    models.PositiveIntegerField(default=0, verbose_name="Share Count"),
                ),
                (
                    "capabilities",
                    models.ManyToManyField(to="caps.capability", verbose_name="Capability"),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="caps_test.concreteobjectreference",
                        verbose_name="Source Reference",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="caps.agent"),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reference_set",
                        to="caps_test.concreteobject",
                        verbose_name="Target",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {("origin", "receiver", "target")},
            },
            bases=(caps.models.capability_set.BaseCapabilitySet, models.Model),
        ),
    ]
