# Generated by Django 5.1.7 on 2025-04-17 08:20

import caps.models.capability_set
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("caps", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConcreteObject",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=16)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ConcreteObjectReference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, verbose_name="Reference")),
                (
                    "depth",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="The amount of time a reference can be re-shared.",
                        verbose_name="Share limit",
                    ),
                ),
                (
                    "expiration",
                    models.DateTimeField(
                        blank=True,
                        help_text="Defines an expiration date after which the reference is not longer valid.",
                        null=True,
                        verbose_name="Expiration",
                    ),
                ),
                (
                    "emitter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emit_references",
                        to="caps.agent",
                        verbose_name="Emitter",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="derived",
                        to="caps_test.concreteobjectreference",
                        verbose_name="Source Reference",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="references",
                        to="caps.agent",
                        verbose_name="Receiver",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="references",
                        to="caps_test.concreteobject",
                        verbose_name="Target",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "proxy": False,
            },
            bases=(caps.models.capability_set.CapabilitySet, models.Model),
        ),
        migrations.CreateModel(
            name="ConcreteObjectReferenceCapability",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("max_derive", models.PositiveIntegerField(default=0, verbose_name="Maximum Derivation")),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="capabilities", to="auth.permission"
                    ),
                ),
                (
                    "reference",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capabilities",
                        to="caps_test.concreteobjectreference",
                        verbose_name="Reference",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "proxy": False,
            },
        ),
    ]
