# Generated by Django 5.2.7 on 2026-01-12 12:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("caps", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agent",
            options={"verbose_name": "Agent", "verbose_name_plural": "Agents"},
        ),
    ]
